create index idx_workspaces_org_id on workspaces(org_id);
create index idx_workspace_members_workspace_id on workspace_members(workspace_id);
create index idx_workspace_members_user_id on workspace_members(user_id);
create index idx_assets_workspace_id on assets(workspace_id);
create index idx_assets_type on assets(type);
create index idx_assets_created_at on assets(created_at desc);
create index idx_assets_deleted_at on assets(deleted_at) where deleted_at is null;
create index idx_jobs_workspace_id on generation_jobs(workspace_id);
create index idx_jobs_status on generation_jobs(status);
create index idx_jobs_user_id on generation_jobs(user_id);
create index idx_ledger_org_id on credit_ledger(org_id);
create index idx_ledger_workspace_id on credit_ledger(workspace_id);
create index idx_ledger_created_at on credit_ledger(created_at desc);
create index idx_invitations_token on invitations(token);
create index idx_invitations_email on invitations(email);
