name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # Assumes you add GCP_CREDENTIALS to your GitHub Actions Secrets
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Run Deploy Script
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: |
          chmod +x deploy.sh
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ./deploy.sh prod
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            ./deploy.sh staging
          fi
